name: Question
description: Ask a question about usage or behavior
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about statistika? Ask away!

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant code, configuration, or background information.
      render: typescript

  - type: input
    id: version
    attributes:
      label: statistika version
      placeholder: "1.0.0"
